insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Sobe - Cranberry Grapefruit', 14);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Gin - Gilbeys London, Dry', 73);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Chips - Doritos', 67);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Rice Paper', 27);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Wine - Balbach Riverside', 2);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Cheese Cloth', 79);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Broccoli - Fresh', 36);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Oil - Food, Lacquer Spray', 9);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Kippers - Smoked', 44);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Absolut Citron', 44);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Sorrel - Fresh', 19);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Sauce - Soy Low Sodium - 3.87l', 41);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Pate - Liver', 33);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Cheese - Pont Couvert', 71);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Sprouts - Baby Pea Tendrils', 52);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Beans - Kidney White', 33);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Bread Base - Italian', 74);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Tomatoes - Hot House', 29);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Flour - Chickpea', 65);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Beef - Tenderlion, Center Cut', 28);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Juice Peach Nectar', 71);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Wine - Red, Pelee Island Merlot', 33);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Pastry - Carrot Muffin - Mini', 58);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Appetizer - Lobster Phyllo Roll', 97);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Ham - Cooked', 70);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Wine - Alsace Gewurztraminer', 24);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Wine - Magnotta, White', 12);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Cherries - Frozen', 52);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Sea Bass - Fillets', 56);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'V8 - Tropical Blend', 21);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Tart Shells - Sweet, 4', 63);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Crab - Back Fin Meat, Canned', 57);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Wine - Jackson Triggs Okonagan', 10);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Coconut - Shredded, Sweet', 99);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Tequila Rose Cream Liquor', 93);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Pasta - Fettuccine, Egg, Fresh', 8);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Lid Tray - 16in Dome', 20);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Duck - Legs', 13);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Bread - Corn Muffaletta', 51);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Mousse - Passion Fruit', 17);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Mushroom - Shitake, Fresh', 61);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Versatainer Nc - 888', 51);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Rum - Light, Captain Morgan', 24);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Alize Red Passion', 7);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Bacardi Limon', 97);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Beer - Sleemans Cream Ale', 1);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Instant Coffee', 7);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Wine - Red, Harrow Estates, Cab', 94);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Egg Patty Fried', 26);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Veal - Osso Bucco', 16);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Olives - Morracan Dired', 83);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Beets - Golden', 73);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Bread - French Stick', 60);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Wine - Champagne Brut Veuve', 78);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Brandy - Orange, Mc Guiness', 53);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Marjoram - Fresh', 88);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Tart Shells - Savory, 2', 22);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Soup - Knorr, Chicken Noodle', 89);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Veal - Slab Bacon', 70);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Olives - Kalamata', 32);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Wine - Domaine Boyar Royal', 89);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Cup - 4oz Translucent', 7);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Chicken Breast Halal', 20);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Wine - Taylors Reserve', 3);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Macaroons - Two Bite Choc', 5);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Durian Fruit', 27);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Buttons', 40);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Wine - Mondavi Coastal Private', 62);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Sprouts - China Rose', 71);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Island Oasis - Raspberry', 83);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Wine - Chateauneuf Du Pape', 83);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Pastry - Cherry Danish - Mini', 46);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Beans - Black Bean, Dry', 62);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Pasta - Canelloni', 68);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Creamers - 10%', 52);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Vodka - Smirnoff', 94);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Icecream - Dstk Super Cone', 37);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Cabbage - Green', 51);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Chestnuts - Whole,canned', 37);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Flour - Buckwheat, Dark', 74);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Tea - English Breakfast', 18);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Quail - Whole, Boneless', 4);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Cream - 35%', 52);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Chicken - Leg / Back Attach', 52);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Lamb - Rack', 10);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Bread - Triangle White', 15);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (2, 'Artichoke - Fresh', 75);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Lettuce Romaine Chopped', 20);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Mushroom - Chanterelle Frozen', 8);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Beer - Upper Canada Light', 87);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Shrimp, Dried, Small / Lb', 73);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Muffin Orange Individual', 17);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Flour - Pastry', 94);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (4, 'Soup - Base Broth Chix', 30);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Pasta - Penne, Lisce, Dry', 17);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Compound - Raspberry', 85);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Soup Campbells Turkey Veg.', 38);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (1, 'Bread Foccacia Whole', 87);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Wine - Sauvignon Blanc Oyster', 36);
insert into Food (Food_TypeID, Food_Name, Food_Price) values (3, 'Anchovy Fillets', 26);
