insert into StaffTitle (Tittle_Desc) values ('Civil Engineer');
insert into StaffTitle (Tittle_Desc) values ('Help Desk Technician');
insert into StaffTitle (Tittle_Desc) values ('Actuary');
insert into StaffTitle (Tittle_Desc) values ('Web Developer IV');
insert into StaffTitle (Tittle_Desc) values ('Web Developer II');
insert into StaffTitle (Tittle_Desc) values ('Business Systems Development Analyst');
insert into StaffTitle (Tittle_Desc) values ('Paralegal');
insert into StaffTitle (Tittle_Desc) values ('Analyst Programmer');
insert into StaffTitle (Tittle_Desc) values ('Electrical Engineer');
insert into StaffTitle (Tittle_Desc) values ('Geological Engineer');
insert into StaffTitle (Tittle_Desc) values ('Clinical Specialist');
insert into StaffTitle (Tittle_Desc) values ('Human Resources Manager');
insert into StaffTitle (Tittle_Desc) values ('Senior Sales Associate');
insert into StaffTitle (Tittle_Desc) values ('Dental Hygienist');
insert into StaffTitle (Tittle_Desc) values ('Chemical Engineer');
insert into StaffTitle (Tittle_Desc) values ('Database Administrator I');
insert into StaffTitle (Tittle_Desc) values ('Safety Technician I');
insert into StaffTitle (Tittle_Desc) values ('Chemical Engineer');
insert into StaffTitle (Tittle_Desc) values ('Statistician II');
insert into StaffTitle (Tittle_Desc) values ('Desktop Support Technician');
