-- -- create table Order
-- -- (
-- --   Report_ID int not null
-- --     constraint [Order]
-- --       references [Report_Date] (Report_ID),
-- --   Order_No int identity
-- --     constraint Order_pk
-- --       primary key nonclustered,
-- --   Customer_ID int not null
-- --     constraint [Order]
-- --       references [Customer] (Customer_ID),
-- --   FoodMenu_ID int not null
-- --     constraint [Order]
-- --       references [Food] (Food_ID),
-- --   Dessert_MenuID int not null
-- --     constraint [Order]
-- --       references [Dessert] (Dessert_ID),
-- --   TaxOrder_ID int not null
-- --     constraint [Order]
-- --       references [Tax] (TaxOrder_ID),
-- --   Rental_ID int not null
-- --     constraint [Order]
-- --       references [Late_Fee_Total] (Rental_ID),
-- --   SupplyOrder_ID int not null
-- --     constraint [Order]
-- --       references [Supply_Total] (SupplyOrder_ID),
-- --   Delivery_ID int not null
-- --     constraint [Order]
-- --       references [Delivery] (Delivery_ID),
-- --   Staff_ID int not null
-- --     constraint [Order]
-- --       references [Staff] (Staff_ID),
-- --   GratuityOrder_ID int not null
-- --     constraint [Order]
-- --       references [Gratuity] (GratuityOrder_ID),
-- --   Drink_MenuID int not null
-- --     constraint [Order]
-- --       references [Drink] (Drink_ID),
-- --   Order_Status int not null,
-- --   Order_Total int not null
-- -- )
-- -- go
--
--
-- create table [Order]
-- (
--   Order_no int identity
--     constraint Order_pk
--       primary key nonclustered,
--   Report_ID int not null
--     constraint Order_ReportDate_Report_ID_fk
--       references ReportDate,
--   Customer_ID int not null,
-- --     constraint Order_Customer_CUSTOMER_ID_fk
-- --       references Customer,
--   FoodMenu_ID int not null,
-- --     constraint Order_MenuTotal_FoodMenu_ID_fk
-- --       references MenuTotal (FoodMenu_ID),
--   Dessert_MenuID int not null,
-- --     constraint Order_DessertMenu_Dessert_MenuID_fk
-- --       references DessertMenu (Dessert_MenuID),
--   TaxOrder_ID int not null,
-- --     constraint Order_Tax_TaxOrder_ID_fk
-- --       references Tax (TaxOrder_ID),
--   Rental_ID int not null,
-- --     constraint Order_Late_fee_Rental_ID_fk
-- --       references Late_fee (Rental_ID),
--   SupplyOrder_ID int not null,
-- --     constraint Order_SupplyTotal_SupplyOrder_ID_fk
-- --       references SupplyTotal (SupplyOrder_ID),
--   Delivery_ID int not null
--     constraint Order_Delivery_DELIVERY_ID_fk
--       references Delivery,
--   Staff_ID int not null,
-- --     constraint Order_Staff_Staff_ID_fk
-- --       references Staff (Staff_ID),
--   GratuityOrder_ID int not null,
-- --     constraint Order_Gratuity_GratuityOrder_ID_fk
-- --       references Gratuity (GratuityOrder_ID),
--   Drink_MenuID int not null,
-- --     constraint Order_DrinkMenu_Drink_MenuID_fk
-- --       references DrinkMenu (Drink_MenuID),
-- --   Order_Status int references Order_Status (Order_Status),
--   Order_Total money not null
-- )
-- go